micronaut:
    application:
        name: centre-tenant-resolver
    server:
        port: 8082
        cors:
            enabled: true

hibernate:
    hbm2ddl:
        auto: 'none'

grails:
    gorm:
        multiTenancy:
            mode: DATABASE
            tenantResolverClass: 'centre.tenant.resolver.tenant.resolver.CustomTenantResolver'

dataSource:
    dbCreate: validate
    driverClassName: com.mysql.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    url: jdbc:mysql://localhost:3306/centre_database_config?useSSL=false
    username: root
    password: root

dataSources:
    cubo:
        dbCreate: validate
        url: jdbc:mysql://localhost:3306/cubo?useSSL=false
        username: root
        password: root
    fviberi:
        dbCreate: validate
        url: jdbc:mysql://localhost:3306/cubo?useSSL=false
        username: root
        password: root
