micronaut:
    application:
        name: centre-tenant-resolver
    server:
        port: 8082
        cors:
            enabled: true

hibernate:
    hbm2ddl:
        auto: 'update'

grails:
    gorm:
        multiTenancy:
            mode: DATABASE
#            tenantResolverClass: 'io.micronaut.multitenancy.gorm.HttpHeaderTenantResolver'
            tenantResolverClass: 'centre.tenant.resolver.tenant.resolver.CustomTenantResolver'

dataSource:
    dbCreate: validate
    driverClassName: com.mysql.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    url: jdbc:mysql://localhost:3306/centre_database_config
    username: root
    password: root